[2025-02-10T09:09:11.164+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_bigquery-test.get_csv_data manual__2025-02-10T09:07:59.618419+00:00 [queued]>
[2025-02-10T09:09:11.185+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_bigquery-test.get_csv_data manual__2025-02-10T09:07:59.618419+00:00 [queued]>
[2025-02-10T09:09:11.186+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2025-02-10T09:09:11.225+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): get_csv_data> on 2025-02-10 09:07:59.618419+00:00
[2025-02-10T09:09:11.234+0000] {standard_task_runner.py:60} INFO - Started process 1380 to run task
[2025-02-10T09:09:11.241+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'load_bigquery-test', 'get_csv_data', 'manual__2025-02-10T09:07:59.618419+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/load-bigquery-test.py', '--cfg-path', '/tmp/tmp1nv7qc63']
[2025-02-10T09:09:11.245+0000] {standard_task_runner.py:88} INFO - Job 25: Subtask get_csv_data
[2025-02-10T09:09:11.276+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.9/site-packages/airflow/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-10T09:09:11.346+0000] {task_command.py:423} INFO - Running <TaskInstance: load_bigquery-test.get_csv_data manual__2025-02-10T09:07:59.618419+00:00 [running]> on host deproject-airflow-scheduler
[2025-02-10T09:09:11.514+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='dibimbing' AIRFLOW_CTX_DAG_ID='load_bigquery-test' AIRFLOW_CTX_TASK_ID='get_csv_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-10T09:07:59.618419+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-10T09:07:59.618419+00:00'
[2025-02-10T09:09:12.091+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/load-bigquery-test.py", line 26, in get_data
    df = pd.read_csv('/opt/bitnami/spark/data/test.output.csv')
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/parsers.py", line 1867, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
    self.handles = get_handle(
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/common.py", line 642, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/opt/bitnami/spark/data/test.output.csv'
[2025-02-10T09:09:12.123+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=load_bigquery-test, task_id=get_csv_data, execution_date=20250210T090759, start_date=20250210T090911, end_date=20250210T090912
[2025-02-10T09:09:12.156+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 25 for task get_csv_data ([Errno 2] No such file or directory: '/opt/bitnami/spark/data/test.output.csv'; 1380)
[2025-02-10T09:09:12.219+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-02-10T09:09:12.264+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
