[2025-02-20T08:55:25.705+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scraping_news_dag.scraping_nyt manual__2025-02-20T08:55:23.701278+00:00 [queued]>
[2025-02-20T08:55:25.727+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scraping_news_dag.scraping_nyt manual__2025-02-20T08:55:23.701278+00:00 [queued]>
[2025-02-20T08:55:25.728+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2025-02-20T08:55:25.759+0000] {taskinstance.py:2214} INFO - Executing <Task(_PythonDecoratedOperator): scraping_nyt> on 2025-02-20 08:55:23.701278+00:00
[2025-02-20T08:55:25.768+0000] {standard_task_runner.py:60} INFO - Started process 10854 to run task
[2025-02-20T08:55:25.776+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'scraping_news_dag', 'scraping_nyt', 'manual__2025-02-20T08:55:23.701278+00:00', '--job-id', '179', '--raw', '--subdir', 'DAGS_FOLDER/scraping-news-dag.py', '--cfg-path', '/tmp/tmp6m6mmkgh']
[2025-02-20T08:55:25.781+0000] {standard_task_runner.py:88} INFO - Job 179: Subtask scraping_nyt
[2025-02-20T08:55:25.820+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.9/site-packages/airflow/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-20T08:55:25.887+0000] {task_command.py:423} INFO - Running <TaskInstance: scraping_news_dag.scraping_nyt manual__2025-02-20T08:55:23.701278+00:00 [running]> on host deproject-airflow-scheduler
[2025-02-20T08:55:26.061+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='scraping_news_dag' AIRFLOW_CTX_TASK_ID='scraping_nyt' AIRFLOW_CTX_EXECUTION_DATE='2025-02-20T08:55:23.701278+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-20T08:55:23.701278+00:00'
[2025-02-20T08:55:27.273+0000] {logger.py:11} INFO - ====== WebDriver manager ======
[2025-02-20T08:55:27.708+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2025-02-20T08:55:27.889+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2025-02-20T08:55:28.043+0000] {logger.py:11} INFO - Driver [/home/airflow/.wdm/drivers/chromedriver/linux64/133.0.6943.126/chromedriver-linux64/chromedriver] found in cache
[2025-02-20T08:56:22.544+0000] {logging_mixin.py:188} INFO - Total scraped: 110
[2025-02-20T08:58:06.456+0000] {logging_mixin.py:188} INFO - Total scraped: 100
[2025-02-20T08:59:48.521+0000] {logging_mixin.py:188} INFO - Total scraped: 110
[2025-02-20T09:01:05.487+0000] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-02-20T09:01:05.496+0000] {process_utils.py:131} INFO - Sending 15 to group 10854. PIDs of all processes in the group: [10880, 10886, 10890, 10893, 10918, 11055, 14678, 10919, 10977, 14758, 14781, 14799, 14810, 10917, 10854]
[2025-02-20T09:01:05.497+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 10854
[2025-02-20T09:01:05.503+0000] {taskinstance.py:2480} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-02-20T09:01:05.520+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))': /session/49f042d32e4c143573bb2457f59340aa
[2025-02-20T09:01:05.535+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff9c27e2430>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/49f042d32e4c143573bb2457f59340aa
[2025-02-20T09:01:05.537+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff9c27e2580>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/49f042d32e4c143573bb2457f59340aa
[2025-02-20T09:01:05.567+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=10880, status='terminated', started='08:55:27') (10880) terminated with exit code None
[2025-02-20T09:01:05.622+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=14678, status='terminated', started='09:00:56') (14678) terminated with exit code None
[2025-02-20T09:01:05.624+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=14781, status='terminated', started='09:01:02') (14781) terminated with exit code None
[2025-02-20T09:01:05.625+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=10917, status='terminated', started='08:55:28') (10917) terminated with exit code None
[2025-02-20T09:01:05.678+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=10977, status='terminated', started='08:55:28') (10977) terminated with exit code None
[2025-02-20T09:01:05.680+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=10854, status='terminated', exitcode=0, started='08:55:25') (10854) terminated with exit code 0
[2025-02-20T09:01:05.681+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=14799, status='terminated', started='09:01:04') (14799) terminated with exit code None
[2025-02-20T09:01:05.683+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=14810, status='terminated', started='09:01:04') (14810) terminated with exit code None
[2025-02-20T09:01:05.684+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=14758, status='terminated', started='09:01:00') (14758) terminated with exit code None
[2025-02-20T09:01:05.686+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=10890, status='terminated', started='08:55:28') (10890) terminated with exit code None
[2025-02-20T09:01:05.687+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=10918, status='terminated', started='08:55:28') (10918) terminated with exit code None
[2025-02-20T09:01:05.688+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=10886, status='terminated', started='08:55:28') (10886) terminated with exit code None
[2025-02-20T09:01:05.690+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=10919, status='terminated', started='08:55:28') (10919) terminated with exit code None
[2025-02-20T09:01:05.691+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=11055, status='terminated', started='08:55:35') (11055) terminated with exit code None
[2025-02-20T09:01:05.693+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=10893, status='terminated', started='08:55:28') (10893) terminated with exit code None
