[2025-02-11T12:30:16.729+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_bigquery-test.get_csv_data manual__2025-02-11T12:29:08.596807+00:00 [queued]>
[2025-02-11T12:30:16.747+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_bigquery-test.get_csv_data manual__2025-02-11T12:29:08.596807+00:00 [queued]>
[2025-02-11T12:30:16.749+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2025-02-11T12:30:16.778+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): get_csv_data> on 2025-02-11 12:29:08.596807+00:00
[2025-02-11T12:30:16.787+0000] {standard_task_runner.py:60} INFO - Started process 991 to run task
[2025-02-11T12:30:16.792+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'load_bigquery-test', 'get_csv_data', 'manual__2025-02-11T12:29:08.596807+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/load-bigquery-test.py', '--cfg-path', '/tmp/tmpzp9f75ib']
[2025-02-11T12:30:16.795+0000] {standard_task_runner.py:88} INFO - Job 49: Subtask get_csv_data
[2025-02-11T12:30:16.825+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.9/site-packages/airflow/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-11T12:30:16.896+0000] {task_command.py:423} INFO - Running <TaskInstance: load_bigquery-test.get_csv_data manual__2025-02-11T12:29:08.596807+00:00 [running]> on host deproject-airflow-scheduler
[2025-02-11T12:30:17.130+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='dibimbing' AIRFLOW_CTX_DAG_ID='load_bigquery-test' AIRFLOW_CTX_TASK_ID='get_csv_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-11T12:29:08.596807+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-11T12:29:08.596807+00:00'
[2025-02-11T12:30:17.577+0000] {logging_mixin.py:188} INFO -    product_id  customer_id  ...     name.1  price.1
0           1            1  ...  Product A    19.99
1           2            2  ...  Product B     9.99
2           3            3  ...  Product C    15.99
3           4            1  ...  Product D     5.99
4           5            2  ...  Product E    12.99
5           6            3  ...  Product F     9.99
6           7            4  ...  Product G    11.99
7           8            1  ...  Product H    14.99
8           9            2  ...  Product I     9.99
9          10            3  ...  Product J    19.99

[10 rows x 9 columns]
[2025-02-11T12:30:22.297+0000] {logging_mixin.py:188} INFO - Data Load Error: Reason: 400 POST https://bigquery.googleapis.com/upload/bigquery/v2/projects/operating-ethos-407708/jobs?uploadType=multipart: Invalid field name "name.1". Fields must contain the allowed characters, and be at most 300 characters long. For allowed characters, please refer to https://cloud.google.com/bigquery/docs/schemas#column_names
[2025-02-11T12:30:22.298+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-02-11T12:30:22.320+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=load_bigquery-test, task_id=get_csv_data, execution_date=20250211T122908, start_date=20250211T123016, end_date=20250211T123022
[2025-02-11T12:30:22.415+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-02-11T12:30:22.450+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
