[2025-02-10T08:06:55.588+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_bigquery-test.fetch_spark_result manual__2025-02-10T08:06:54.492347+00:00 [queued]>
[2025-02-10T08:06:55.612+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_bigquery-test.fetch_spark_result manual__2025-02-10T08:06:54.492347+00:00 [queued]>
[2025-02-10T08:06:55.613+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2025-02-10T08:06:55.646+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): fetch_spark_result> on 2025-02-10 08:06:54.492347+00:00
[2025-02-10T08:06:55.654+0000] {standard_task_runner.py:60} INFO - Started process 2642 to run task
[2025-02-10T08:06:55.660+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'load_bigquery-test', 'fetch_spark_result', 'manual__2025-02-10T08:06:54.492347+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/load-bigquery-test.py', '--cfg-path', '/tmp/tmp9dmiaj_o']
[2025-02-10T08:06:55.664+0000] {standard_task_runner.py:88} INFO - Job 9: Subtask fetch_spark_result
[2025-02-10T08:06:55.696+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.9/site-packages/airflow/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-10T08:06:55.767+0000] {task_command.py:423} INFO - Running <TaskInstance: load_bigquery-test.fetch_spark_result manual__2025-02-10T08:06:54.492347+00:00 [running]> on host deproject-airflow-scheduler
[2025-02-10T08:06:55.966+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='dibimbing' AIRFLOW_CTX_DAG_ID='load_bigquery-test' AIRFLOW_CTX_TASK_ID='fetch_spark_result' AIRFLOW_CTX_EXECUTION_DATE='2025-02-10T08:06:54.492347+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-10T08:06:54.492347+00:00'
[2025-02-10T08:06:55.969+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/load-bigquery-test.py", line 26, in fetch_spark_result
    result = ti.xcom_pull(tasks_ids="extract_spark_output", key="df_result")
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
TypeError: xcom_pull() got an unexpected keyword argument 'tasks_ids'
[2025-02-10T08:06:55.993+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=load_bigquery-test, task_id=fetch_spark_result, execution_date=20250210T080654, start_date=20250210T080655, end_date=20250210T080655
[2025-02-10T08:06:56.020+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 9 for task fetch_spark_result (xcom_pull() got an unexpected keyword argument 'tasks_ids'; 2642)
[2025-02-10T08:06:56.075+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-02-10T08:06:56.111+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
